### PR TITLE
Upgrade plugin for 0.4.x

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by cjblomqvist** [comment]
Looks good to me, except you changed the installation instructions to point to the dokku repo, although there is no such repo yet? You want me to move my fork there out are you planning on forking my repo or is it a mistake?

**Comment by josegonzalez** [comment]
Woops I'm a noob. Will fix!

**Comment by josegonzalez** [comment]
_bump_

**Comment by cjblomqvist** [comment]
Sorry, missed your commit!

**Comment by josegonzalez** [comment]
<3

**Pull request merged**
