### PR TITLE
Simplify plugin

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by cjblomqvist** [comment]
I haven't tested it myself but my experience with your work is very good so I trust it will work. Looks in general to be a nice simplification and cleanup!

**Comment by timaschew** [comment]
Is that also fixing the issue that an old hash is used (sometimes)?

**Comment by timaschew** [comment]
This is what I realized, inside of the host:

```
root@v22016101411038859:/home/dokku/sas-admin# cat .dokku-git-rev
2ace11b3cde5c0125b569ffdfa78854e9a5c1f66
```
This is the latest hash.

But if I run a bash inside of the container I get an old hash for this command

```
herokuishuser@d43e0fe9d9dd:~$ pwd
/app
herokuishuser@d43e0fe9d9dd:~$ cat .profile.d/git_rev.sh
export GIT_REV=1e3bf1ca4d02509beabb9b9b99c2b2d3e8b505d8
```
which is and old git hash

**Comment by josegonzalez** [comment]
My changes no longer use those files, and instead set the env var directly.

**Comment by timaschew** [comment]
I still have the issue. But I'm not sure if the update was successful. How can I verify it?  Is the source code available in any directory?

**Comment by josegonzalez** [comment]
When you install a plugin, they get installed to `$DOKKU_LIB_ROOT/plugins/available`. `$DOKKU_LIB_ROOT` is usually `/var/lib/dokku`.

**Comment by timaschew** [comment]
Okay looks, good, `git log` shows also the commit hash of this PR. But somehow I still have always the git hash of the previous build in my app via the `GIT_REV` env

**Comment by josegonzalez** [comment]
Did you install the plugin to `dokku-git-rev`?

**Pull request merged**
